language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true

before_install:
  - composer self-update

install:
  - composer install --no-interaction --no-suggest --no-progress
  - composer create-project phpstan/phpstan temp/phpstan --no-dev --no-progress
  - composer create-project aipng/coding-standard temp/coding-standard --no-progress

script:
  - ./vendor/bin/tester -s ./tests/
  - temp/phpstan/bin/phpstan analyze -l 7 ./src
  - temp/coding-standard/phpcs ./src ./tests

after_failure:
  # Vytiskne obsah souborů *.actual
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
